public class staticExamples {
 
    
    
    
   public  static  void show(){
        
     Integer [] arr = new integer [5] ;
       
       
       System.debug('values inside the array '+arr);
       
       
       
       integer a = 10;
       integer b =11;
       
       if(a==b)
       {
            System.debug('i am in if block');
           System.debug('the value of a and b are equal');
       }else{

			 System.debug('i am in else block');
			  System.debug('the value of a and b are not equal');    
           
       }
       
      
    }


}